### ISSUE TITLE
app funciona no smartphone (emulator) mas não funciona no emulator do android wear api 23

### ISSUE THREAD

**Issue by ghost** [netomarin/pomodroid#1]
06-22 18:30:47.154 6599-6599/br.com.netomarin.pomodroid W/System: ClassLoader referenced unknown path: /data/app/br.com.netomarin.pomodroid-1/lib/x86
06-22 18:30:47.163 6599-6599/br.com.netomarin.pomodroid D/AndroidRuntime: Shutting down VM
06-22 18:30:47.163 6599-6599/br.com.netomarin.pomodroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: br.com.netomarin.pomodroid, PID: 6599
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.netomarin.pomodroid/br.com.netomarin.pomodroid.PomodroidMainActivity}: android.util.AndroidRuntimeException: You cannot combine swipe dismissal and the action bar.
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           Caused by: android.util.AndroidRuntimeException: You cannot combine swipe dismissal and the action bar.
                                                                              at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:337)
                                                                              at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3689)
                                                                              at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
                                                                              at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:383)
                                                                              at android.app.Activity.setContentView(Activity.java:2172)
                                                                              at br.com.netomarin.pomodroid.PomodroidMainActivity.onCreate(PomodroidMainActivity.java:38)
                                                                              at android.app.Activity.performCreate(Activity.java:6251)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ghost** [comment]
Resolvi usando (emulador wear bluetooth) e este site: http://stackoverflow.com/questions/24587218/android-util-androidruntimeexception-you-cannot-combine-swipe-dismissal-and-the

**Mexi no manifest.xml em:** 
<uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="23" />

**e**

android:theme="@style/AppTheme" >
**Change the above line to**
android:theme="@android:style/Theme.DeviceDefault" >
